version: '3'

services:
  demobook:
    depends_on:
      - redis
    build:
      context: '.'
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    env_file:
      - .env
  redis:
    image: 'redis:alpine'
    command: redis-server --appendonly yes
    volumes:
      - 'redis-data:/data'

volumes:
  redis-data:
    driver: local
